### ISSUE TITLE
`carthage update --platform iOS` failed in Xcode 11

### ISSUE THREAD

**Issue by Lebron1992** [kickstarter/Kickstarter-ReactiveExtensions#80]
Hi,
After updated to Xcode 11, when I executed `carthage update --platform iOS`, I got this error:

```
The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal armv7 com.apple.xcode.tools.swift.compiler
```

It works in Xcode 10 before. Any update to fix the issues in Xcode 11? Thank you.

**Comment by nthtrung09it** [comment]
@Lebron1992 did you solve it?

**Comment by Lebron1992** [comment]
@jamielynnroth  Yes! I forked the repository and fixed the issue like this: https://github.com/Lebron1992/Kickstarter-ReactiveExtensions/commit/ca234ddab4d6e338148a21f7a5b73471c41aefbe
